
num1 = input("Enter First number: ")
# check if num1 is zero say semester not pass then exit
# ...
#check if num1 is smaller than zero say number is not valid then exit
# ...
#check if num1 is bigger than ten say number is not valid then exit
# ...
num2 = input("Enter Second number: ")
# check if num2 is zero say semester not pass then exit
# ...
#check if num2 is smaller than zero say number is not valid then exit
# ...
#check if num2 is bigger than ten say number is not valid then exit
# ...
num3 = input("Enter Third number: ")
# check if num3 is zero say semester not pass then exit
# ...
#check if num3 is smaller than zero say number is not valid then exit
# ...
#check if num3 is bigger than ten say number is not valid then exit
# ...
num4 = input("Enter Fourth number: ")  
# check if num4 is zero say semester not pass then exit
# ...
#check if num4 is smaller than zero say number is not valid then exit
# ...
#check if num4 is bigger than ten say number is not valid then exit
# ...    
num5 = input("Enter Fifth number: ")
# check if num5 is zero say semester not pass then exit
# ...
#check if num5 is smaller than zero say number is not valid then exit
# ...
#check if num5 is bigger than ten say number is not valid then exit
# ...  

sum = float(num1) + float(num2) + float(num3) + float(num4) + float(num5)
avg = sum / 5
# check if avg is less than 7 say semester not pass 
# check else say semester pass
