# Exercise Three:
# Write a python program average calculation for a class of ten students.
a = float(input("Num1: "))
b = float(input("Num2: "))
c = float(input("Num3: "))
d = float(input("Num4: "))
e = float(input("Num5: "))
f = float(input("Num6: "))
g = float(input("Num7: "))
h = float(input("Num8: "))
i = float(input("Num9: "))
j = float(input("Num10: "))
s = (a) + (b) + (c) + (d) + (e) + (f) + (g) + (h) + (i) + (j)
print(s/10)
# Hint: Use typecasting. Like float(input("Enter a number: "))
# ---- 
# num1 = int(input("Enter first number "))
# num2 = int(input("Enter second number "))
# res = num1 * num2
# print("Multiplication is", res)

num1 = float(input("Enter first number "))
num2 = float(input("Enter second number "))
num3 = float(input("Enter third number "))
num4 = float(input("Enter fourth number "))
num5 = float(input("Enter fifth number "))
num6 = float(input("Enter sixth number "))
num7 = float(input("Enter seventh number "))
num8 = float(input("Enter eighth number "))
num9 = float(input("Enter ninth number "))
num10 = float(input("Enter tenth number "))
sum = (num1) + (num2) + (num3) + (num4) + (num5) + (num6) + (num7) + (num8) + (num9) + (num10)
print("Sum of all numbers is", sum)
final = sum / 10
prtin("Average of all numbers is", final)